#----------------------------------------------------------------
# AppVeyor CI for R Packages
# https://github.com/krlmlr/r-appveyor
# Validator: https://ci.appveyor.com/tools/validate-yaml
#----------------------------------------------------------------
environment:
  global:
    USE_RTOOLS: true
    _R_CHECK_FORCE_SUGGESTS_: false

  matrix:
  - R_VERSION: devel
    BIOC_USE_DEVEL: TRUE
    R_ARCH: x64
      
  - R_VERSION: devel
    BIOC_USE_DEVEL: TRUE
    R_ARCH: i386

  - R_VERSION: release
    BIOC_USE_DEVEL: FALSE
    R_ARCH: x64

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest https://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: |
        Bootstrap

cache:
  - C:\RLibrary -> appveyor.yml

build_script:
  - echo Current directory=%CD%
  - travis-tool.sh install_deps
  - travis-tool.sh install_r markdown R.rsp
  - travis-tool.sh install_r future.BatchJobs future.batchtools
  - travis-tool.sh install_bioc BiocParallel
  
test_script:
  - travis-tool.sh run_tests

after_test:
  - 7z a all-Rout.zip *.Rcheck\**\*.Rout *.Rcheck\**\*.fail

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: all-Rout.zip
    name: AllRout

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
